john/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('john.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

john/models.py
from django.db import models

# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=200)
    greetings_1 = models.CharField(max_length=50)
    greetings_2 = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                                on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)



# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=200)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=200)

    

# PORTFOLIO SECTION

class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')

    def __str__(self):
        return f'Portfolio {self.id}'

john/views.py
from django.shortcuts import render
from .models import Home, About, Profile, Category, Skills, Portfolio

def index(request):

    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.order_by('-updated')
    profiles = Profile.objects.filter(about=about)

    # Skills
    categories = Category.objects.all()

    # Portfolio
    portfolios = Portfolio.objects.all()
    

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios
    }


    return render(request, 'index.html', context)

john/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>PTPW</title>
        
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                    

                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Services</a></li>
                        <li class="nav__item"><a href="#reviews" class="nav__link">Reviews</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Gallery</a></li>
                        

                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                        
                        </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
        
    
</div>

        <main class="l-main">

            <!--===== HOME =====-->
            
            <section class="home" id="home" style="background-size:cover; background-image: url('{% static "assets/img/cx.jpg"%}')";>
            

                <div class="home__container bd-grid">

                
                   <h1 class="home__title"><span><br>{{ home.greetings_1 }}</span>&nbsp;<br>&nbsp;&nbsp;{{ home.greetings_2 }}</h1>
                   

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{ home.picture.url }}" alt="" class="home__img">

                </div>
                
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <p class="about__profession" style="text-align: center;">Pro Tech Pressure Washing is a commercial soft and power washing service. We aim to provide the following :</p>

                {% for about in about %}

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <!-- <img src="{% static 'assets/img/perfil.png' %}" alt=""> -->
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">

                            {% for profile in about.profile_set.all %}
                                <a href="{{ profile.link }}" class="about__social-icon">
                                    <i class='bx bxl-{{ profile.social_name }}' ></i>
                                </a>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Services</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                            
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        
                    </div>

                    <div class="skills__img text text-center">
                        <img class="" src="{% static 'assets/img/1212.jpg' %}" alt=""style="text-align:center;">
                    </div>
                </div>
            </section>

            <section class="portfolio section" id="reviews" >
            <h2 class="section-title ">Reviews</h2>
                    <p class="about__profession" style="text-align: center;"><small><i>COMING SOON!</i></small></p>


            <div class="about__container bd-grid">
                    
                    

                    
                    

                    
                    
                </div>
               
    
                
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
            <h2 class="section-title">Some photos of what we do!</h2>
            <p class="about__profession" style="text-align: center;"><small><i>Click to view!</i></small></p>


            <div class="portfolio__container bd-grid">
                    
                    {% for portfolio in portfolios %}
                    
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" alt="" style="width:150px;">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.image.url }}" class="portfolio__link-name"><i class="bx bx-image"></i> View</a>
                        </div>
                    </div>

                    {% endfor %}
                    
                </div>

                </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact" style="text-align:center;">
                <h2 class="section-title">Contact Us</h2>

                 <p class="about__profession" style="text-align: center;">Please contact us for a free quote!</p>


                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text"><a href = "mailto: underpressureza@gmail.com">underpressureza@gmail.com</a></span>
<!-- 
                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+20 999-999</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">My contry</span> -->
                    </div>

                    <div class="contact__info">
                    
                        <h3 class="contact__subtitle">PHONE</h3>
                        
                        <span class="contact__text">+27 824 840 822<br>+27 624 216 712</span>
                        
                        
                    </div>
                    

                   </div>
                   

                    </section>
                    
           
        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid "style="text-align:center;">
                <div class="footer__data">
                    <h2 class="footer__title">Pro Tech Pressure  Washing</h2>
                    <p class="footer__text">- Experience the difference.

</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Sevices</a></li>
                        <li><a href="#portfolio" class="footer__link">Gallery</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW US</h2>
                    <a href="https://www.facebook.com/PTPWza/" class="footer__social" target="_blank"><i class='bx bxl-facebook' ></i></a>
                    <a href="https://www.instagram.com/protechpw/" class="footer__social" target="_blank"><i class='bx bxl-instagram' ></i></a>
                </div>
                

            </div><br><br>
            <div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
            <small><p style="text-align:center;"> Copyright &copy; 2021 Pro Tech Pressure Washing - All Rights Reserved</p></small>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<a href="https://api.whatsapp.com/send/?phone=27824840822&text&app_absent=0"
   		 class="float" target="_blank">
<i class="fa fa-whatsapp my-float"></i>

</a>


<!-- CSS -->
<style>
.float:hover {
    background-color:#FFF;
	color:#25d366;
}
.float{
	position:fixed;
	width:60px;
	height:60px;
	bottom:40px;
	right:40px;
	background-color:#25d366;
	color:#FFF;
	border-radius:50px;
	text-align:center;
  font-size:30px;
	box-shadow: 2px 2px 3px black;
  z-index:100;
}

.my-float{
	margin-top:16px;
}
 </style>

     

    </body>
</html>